version: '3'

services:
  postgres:
    image: postgres:16
    container_name: project1_psql
    ports:
      - "5432:5432"
    env_file:
     - ./compose.env
#    environment:
#      POSTGRES_DB: your_database_name
#      POSTGRES_USER: your_username
#      POSTGRES_PASSWORD: your_password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
